### ISSUE TITLE
"Interpreted as" block doesn't appear when custom colour is selected

### ISSUE THREAD

**Issue by gthn** [Maybulb/Nimble2#1]
![image](https://cloud.githubusercontent.com/assets/11558805/25322474/5e2604b6-28af-11e7-8d08-6a89c68f0f32.png)
Whenever a custom colour is selected, the "interpreted as" block does not appear.

**Comment by jmshal** [comment]
I suspect that it is due to the highlight colour, used in the interpretation component, being too light, based on the custom colour you chose. The highlight colour is picked by "lightening" the base color by 30% (https://github.com/Maybulb/Nimble2/blob/master/src/components/Theme/Theme.js#L8).

```diff
 function Theme({ color }) {
   const primary = colors[color] || color;
+  const highlight = Color(primary).lighten(.3).hex();
   const dark = Color(primary).darken(.1).hex();
   return (
     <style>{`
```

**Comment by jmshal** [comment]
In cases where the base colour is too light to choose a viable highlight colour, what do you suggest we do @gthn? I have no problem detecting it, but I'm not sure what colour should be chosen in that case. Maybe we should darken the highlight colour? But that would be inconsistent with the default.

**Comment by jmshal** [comment]
Closing because I found the Nimble 2 design files, and just realised that the interpretation section is completely different, and in the same colour as the primary! Easy!
